name: Releases

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        name: test2
        allowUpdates: true
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "README.md"
        tag: test2-2
        token: ${{ secrets.GITHUB_TOKEN }}
